Publclass Hewam{
    private int jumlah Kaki;
    private String nama Hewan;
    public int getJumlahKaki(){
        retrun jumlahKaki;
    }
    public void setJumlahKak(int jumlahKaki){
        This.jumlahKaki=jumlahKaki;

    }
    public String getNamaHewan(){
        retrun namaHewan;

    }
    public void setNamaHewan(String namaHewan){
     This.namHewan=namaHewan;
       
    }
}